---
settings:
  name: StorageGRID solutions and resources
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: true
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Soluzioni e risorse di StorageGRID
    url: "/index.html"
  - title: Prova StorageGRID
    url: "/evaluation-software.html"
  - section: third-party
  - section: product-feature-guides
  - section: tools-apps-guides
  - section: examples
  - section: technical-reports
  - title: Prova StorageGRID
    url: "/evaluation-software.html"
  - title: Post del blog
    url: "/blogs.html"
  - title: Documentazione StorageGRID
    url: "/storagegrid-documentation.html"
  - title: Note legali
    url: "/legal-notices.html"
