---
settings:
  name: How to enable StorageGRID in your environment
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Come attivare StorageGRID
    url: "/index.html"
  - section: third-party
  - section: product-feature-guides
  - section: tools-apps-guides
  - section: examples
  - title: Post del blog
    url: "/blogs.html"
  - title: Documentazione StorageGRID
    url: "/storagegrid-documentation.html"
