---
permalink: technical-reports/monitor/audit-log-monitoring.html 
sidebar: sidebar 
keywords: audit logs, storagegrid 
summary: 'Scopri come utilizzare l"audit log di StorageGRID per approfondimenti dettagliati sulle attività di tenant e grid e come sfruttare strumenti come Splunk per l"analisi dei log.' 
---
= Utilizzare i registri di controllo per monitorare StorageGRID
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../../media/


[role="lead"]
Scopri come utilizzare l'audit log di StorageGRID per approfondimenti dettagliati sulle attività di tenant e grid e come sfruttare strumenti come Splunk per l'analisi dei log.

L'audit log di StorageGRID consente di raccogliere informazioni dettagliate sul tenant e sull'attività della griglia. L'audit log può essere esposto per analisi tramite NFS. Per istruzioni dettagliate su come esportare il registro di controllo, consultare la Guida dell'amministratore.

Dopo l'esportazione della audit, puoi utilizzare strumenti di analisi dei log come Splunk o Logstash + Elasticsearch per comprendere l'attività dei tenant o creare report dettagliati su fatturazione e charge back.

I dettagli sui messaggi di controllo sono inclusi nella documentazione di StorageGRID. Vedere https://docs.netapp.com/us-en/storagegrid-118/audit/audit-messages-main.html["Messaggi di audit"^].
