---
sidebar: sidebar 
permalink: technical-reports/commvault-s3-consistency-levels.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Scopri alcuni casi di utilizzo per le configurazioni StorageGRID implementate dai clienti e da NetApp IT. 
---
= Suggerimento del livello di coerenza della benna
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp StorageGRID consente all'utente finale di selezionare il livello di coerenza per le operazioni eseguite sugli oggetti nei bucket Simple Storage Service (S3).

CommVault MediaAgent è il data mover di un ambiente CommVault. Nella maggior parte dei casi, i MediaAgent sono configurati per scrivere localmente in un sito StorageGRID primario. Per questo motivo, si consiglia un elevato livello di coerenza all'interno di un sito primario locale. Utilizza le seguenti linee guida quando imposti il livello di coerenza sui bucket CommVault creati in StorageGRID.

[NOTE]
====
Se si dispone di una versione di CommVault precedente alla 11.0.0 - Service Pack 16, valutare la possibilità di aggiornare CommVault alla versione più recente. Se questa opzione non è disponibile, attenersi alle linee guida per la versione in uso.

====
* Versioni di CommVault precedenti alla 11.0.0 - Service Pack 16.* nelle versioni precedenti alla 11.0.0 - Service Pack 16, CommVault esegue S3 TESTE e OTTIENE le operazioni su oggetti inesistenti come parte del processo di ripristino e pruning. Impostare il livello di coerenza del bucket su un sito sicuro per ottenere un livello di coerenza ottimale per i backup CommVault su StorageGRID.
* CommVault versioni 11.0.0 - Service Pack 16 e successive.* nelle versioni 11.0.0 - Service Pack 16 e successive, il numero di operazioni HEAD S3 e GET eseguite su oggetti inesistenti viene ridotto al minimo. Impostare il livello di coerenza del bucket predefinito su Read-after-new-write per garantire un elevato livello di coerenza nell'ambiente CommVault e StorageGRID.

