---
sidebar: sidebar 
permalink: technical-reports/commvault-solution-overview.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Scopri alcuni casi di utilizzo per le configurazioni StorageGRID implementate dai clienti e da NetApp IT. 
---
= Panoramica della soluzione testata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La soluzione collaudata combina le soluzioni CommVault e NetApp per realizzare una potente soluzione congiunta.



== Setup della soluzione

Durante la configurazione in laboratorio, l'ambiente StorageGRID era composto da quattro appliance NetApp StorageGRID SG5712, un nodo amministrativo primario virtuale e un nodo gateway virtuale. L'appliance SG5712 è l'opzione entry-level, una configurazione di base. La scelta di opzioni dalle performance più elevate come NetApp StorageGRID SG5760 o SG6060 può fornire benefici significativi in termini di performance. Per assistenza sul dimensionamento, consulta il Solution Architect NetApp StorageGRID.

Per la policy di protezione dei dati, StorageGRID utilizza una policy di Lifecycle management integrata (ILM) per gestire e proteggere i dati. Le regole ILM vengono valutate in una politica dall'alto verso il basso. Il criterio ILM viene implementato come illustrato nella tabella seguente:

[cols="1a,1a,1a"]
|===
| Regola ILM | Qualificatori | Comportamento di acquisizione 


 a| 
Erasure coding 2+1
 a| 
Oggetti superiori a 200KB
 a| 
Bilanciato



 a| 
2 Copia
 a| 
Tutti gli oggetti
 a| 
Dual commit

|===
La regola di copia di ILM 2 è la regola predefinita. La regola Erasure Coding 2+1 è stata applicata per questo test a qualsiasi oggetto 200KB o superiore. La regola predefinita è stata applicata agli oggetti di dimensioni inferiori a 200KB. L'applicazione delle regole in questo modo è una Best practice di StorageGRID.

Per informazioni tecniche su questo ambiente di test, leggere la sezione progettazione della soluzione e Best practice nella https://www.netapp.com/us/media/tr-4831.pdf["Data Protection scale-out NetApp con CommVault"] report tecnico.



== Specifiche dell'hardware StorageGRID

La tabella seguente descrive l'hardware NetApp StorageGRID utilizzato per questo test. L'appliance StorageGRID SG5712 con connettività di rete 10Gbps è l'opzione entry-level e rappresenta una configurazione di base. In alternativa, SG5712 può essere configurato per il collegamento in rete 25Gbps.

[cols="1a,1a,1a,1a,1a"]
|===
| Hardware | Quantità | Disco | Capacità utilizzabile | Rete 


 a| 
Appliance StorageGRID SG5712
 a| 
4
 a| 
48 x 4TB GB (HDD SAS near-line)
 a| 
136TB
 a| 
10Gbps

|===
La scelta di opzioni di appliance con performance più elevate come le appliance NetApp StorageGRID SG5760, SG6060 o All Flash SGF6112 può fornire benefici significativi in termini di performance. Per assistenza sul dimensionamento, consulta il Solution Architect NetApp StorageGRID.



== Requisiti software CommVault e StorageGRID

Le tabelle seguenti elencano i requisiti software per il software CommVault e NetApp StorageGRID installato sul software VMware ai fini del test. Sono stati installati quattro programmi di gestione della trasmissione dati MediaAgent e un server CommServe. Nel test è stata implementata la connettività di rete 10Gbps per l'infrastruttura VMware. La tabella seguente

La tabella seguente elenca i requisiti di sistema totali del software CommVault:

[cols="1a,1a,1a,1a,1a,1a"]
|===
| Componente | Quantità | Datastore | Dimensione | Totale | Numero totale di IOPS richiesti 


 a| 
CommServe Server
 a| 
1
 a| 
SISTEMA OPERATIVO
 a| 
500GB
 a| 
500GB
 a| 
n/a.



 a| 
 a| 
 a| 
SQL
 a| 
500GB
 a| 
500GB
 a| 
n/a.



 a| 
MediaAgent
 a| 
4
 a| 
CPU virtuale (vCPU)
 a| 
16
 a| 
64
 a| 
n/a.



 a| 
 a| 
 a| 
RAM
 a| 
128GB
 a| 
512
 a| 
n/a.



 a| 
 a| 
 a| 
SISTEMA OPERATIVO
 a| 
500GB
 a| 
2TB
 a| 
n/a.



 a| 
 a| 
 a| 
Cache indice
 a| 
2TB
 a| 
8TB
 a| 
200+



 a| 
 a| 
 a| 
DB
 a| 
2TB
 a| 
8TB
 a| 
200-80.000K

|===
Nell'ambiente di test, sono stati implementati un nodo di amministrazione principale virtuale e un nodo di gateway virtuale su VMware su uno storage array NetApp e-Series E2812. Ciascun nodo si trovava su un server separato con i requisiti minimi dell'ambiente di produzione descritti nella tabella seguente:

Nella tabella seguente sono elencati i requisiti per i nodi amministrativi virtuali StorageGRID e i nodi gateway:

[cols="1a,1a,1a,1a,1a"]
|===
| Tipo di nodo | Quantità | VCPU | RAM | Storage 


 a| 
Nodo gateway
 a| 
1
 a| 
8
 a| 
24GB
 a| 
100GB LUN per il sistema operativo



 a| 
Nodo amministrativo
 a| 
1
 a| 
8
 a| 
24GB
 a| 
100GB LUN per il sistema operativo

200GB LUN per le tabelle dei nodi Admin

200GB LUN per l'audit log del nodo Admin

|===