---
sidebar: sidebar 
permalink: technical-reports/data-security-platform-security.html 
keywords: platform security, storagegrid 
summary: Informazioni sulle funzionalità di sicurezza della piattaforma in StorageGRID. 
---
= Funzioni di sicurezza della piattaforma
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Informazioni sulle funzionalità di sicurezza della piattaforma in StorageGRID.

[cols="20,30a,30,20"]
|===
| Funzione | Funzione | Impatto | Conformità normativa 


| Infrastruttura a chiave pubblica (PKI) interna, certificati dei nodi e TLS  a| 
StorageGRID utilizza un'infrastruttura PKI interna e certificati di nodo per autenticare e crittografare la comunicazione internodale. La comunicazione internodale è protetta da TLS.
| Contribuisce a proteggere il traffico del sistema su LAN o WAN, soprattutto in un'implementazione multisito. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Firewall nodo  a| 
StorageGRID configura automaticamente le tabelle IP e le regole di firewall per controllare il traffico di rete in entrata e in uscita, oltre a chiudere le porte non utilizzate.
| Consente di proteggere il sistema StorageGRID, i dati e i metadati dal traffico di rete non richiesto. | -- 


| Protezione avanzata dei sistemi operativi  a| 
Il sistema operativo di base delle appliance fisiche e dei nodi virtuali StorageGRID è rafforzato; vengono rimossi i pacchetti software non correlati.
| Contribuisce a ridurre al minimo le potenziali superfici di attacco. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Aggiornamenti periodici della piattaforma e del software  a| 
StorageGRID fornisce versioni software regolari che includono il sistema operativo, i file binari delle applicazioni e gli aggiornamenti software.
| Aiuta a mantenere il sistema StorageGRID aggiornato con i software e i file binari delle applicazioni correnti. | -- 


| Accesso root disabilitato su Secure Shell (SSH)  a| 
Il login root su SSH è disabilitato su tutti i nodi StorageGRID. L'accesso SSH utilizza l'autenticazione del certificato.
| Aiuta i clienti a proteggersi da potenziali violazioni remote delle password del login root. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Sincronizzazione automatica dell'ora  a| 
StorageGRID sincronizza automaticamente gli orologi di sistema di ciascun nodo con più server NTP (Time Network Protocol) esterni. Sono necessari almeno quattro server NTP di strato 3 o successivo.
| Garantisce lo stesso riferimento temporale in tutti i nodi. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Separare le reti per il traffico grid interno, amministrativo e client  a| 
I nodi software e le appliance hardware StorageGRID supportano più interfacce di rete virtuali e fisiche, in modo che i clienti possano separare il traffico di client, amministrazione e rete interna su reti diverse.
| Consenti agli amministratori Grid di separare il traffico di rete interno ed esterno e di distribuire il traffico sulle reti con SLA diversi. | -- 


| Interfacce VLAN (Virtual LAN) multiple  a| 
StorageGRID supporta la configurazione delle interfacce VLAN sul client StorageGRID e sulle reti grid.
| Consenti agli amministratori Grid di partizionare e isolare il traffico delle applicazioni per garantire sicurezza, flessibilità e prestazioni. |  


| Rete client non attendibile  a| 
L'interfaccia di rete client non attendibile accetta connessioni in entrata solo su porte che sono state esplicitamente configurate come endpoint di bilanciamento del carico.
| Garantisce la protezione delle interfacce esposte a reti non attendibili. | -- 


| Firewall configurabile  a| 
Gestire le porte aperte e chiuse per le reti Admin, Grid e client.
| Consentire agli amministratori di rete di controllare l'accesso alle porte e di gestire l'accesso alle porte dei dispositivi approvati. |  


| Comportamento SSH avanzato  a| 
disabilitare SSH per impostazione predefinita prima dell'installazione.  Nello stato predefinito, l'accesso SSH è abilitato solo sull'indirizzo delle porte di gestione link-local.  Le password utente admin e root sono impostate sul numero di serie del controller di elaborazione dell'appliance.  L'accesso è consentito solo sulla console seriale e sulla console grafica (BMC KVM).  SSH è disabilitato su qualsiasi porta di rete.
| Migliora la protezione dell'accesso alla rete. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Crittografia dei nodi  a| 
Come parte della nuova funzione di crittografia del server host KMS, viene aggiunta una nuova impostazione di crittografia dei nodi al programma di installazione dell'appliance StorageGRID.
| Questa impostazione deve essere attivata durante la fase di configurazione hardware dell'installazione dell'appliance. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 
|===