---
sidebar: sidebar 
permalink: technical-reports/load-balancer-third-party-load-balancer-configuration.html 
keywords: third-party load balancer, storagegrid 
summary: Scopri come configurare il bilanciamento del carico di terze parti attendibile in StorageGRID. 
---
= Configurare il bilanciamento del carico di terze parti attendibile in StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Scopri come configurare il bilanciamento del carico di terze parti attendibile in StorageGRID.

Se si utilizzano uno o più bilanciatori di carico Layer 7 esterni e un bucket S3 o policy di gruppo basati su IP, StorageGRID deve determinare l'indirizzo IP reale del mittente. Ciò avviene guardando l'intestazione X-Forwarding-for (XFF), che viene inserita nella richiesta dal bilanciatore di carico. Poiché l'intestazione XFF può essere facilmente sottoposta a spoofing nelle richieste inviate direttamente ai nodi di archiviazione, StorageGRID deve confermare che ogni richiesta è stata instradata da un bilanciatore di carico di livello 7 attendibile. Se StorageGRID non è in grado di considerare attendibile l'origine della richiesta, ignorerà l'intestazione XFF. È disponibile un'API di gestione griglia che consente di configurare un elenco di bilanciatori del carico di livello 7 esterni attendibili. Questa nuova API è privata ed è soggetta a modifiche nelle versioni future di StorageGRID. Per le informazioni più aggiornate, vedere l'articolo della Knowledge base, https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_configure_StorageGRID_to_work_with_third-party_Layer_7_load_balancers["Come configurare StorageGRID per il funzionamento con sistemi di bilanciamento del carico Layer 7 di terze parti"^].
