---
sidebar: sidebar 
permalink: technical-reports/data-security/index.html 
keywords: security features, storagegrid 
summary: Scopri le funzionalità di sicurezza integrate della soluzione di storage a oggetti StorageGRID. 
---
= Proteggi dati e metadati StorageGRID in un archivio di oggetti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Scopri le funzionalità di sicurezza integrate della soluzione di storage a oggetti StorageGRID.

Questa è una panoramica delle numerose funzionalità di protezione di NetApp® StorageGRID®, che includono l'accesso ai dati, gli oggetti e i metadati, l'accesso amministrativo e la protezione della piattaforma. È stato aggiornato per includere le funzioni più recenti rilasciate con StorageGRID 11,9.

La sicurezza è parte integrante della soluzione di storage a oggetti NetApp StorageGRID. La sicurezza è particolarmente importante, in quanto molti tipi di dati rich content adatti allo storage a oggetti sono anche sensibili, soggetti a normative e conformità. Con la continua evoluzione delle funzionalità di StorageGRID, il software rende disponibili molte funzionalità di sicurezza preziose per proteggere il livello di sicurezza di un'organizzazione e aiutare l'organizzazione a soddisfare le Best practice del settore.

In questo documento viene fornita una panoramica delle numerose funzioni di protezione di StorageGRID 11,9, suddivise in cinque categorie:

* Funzioni di sicurezza per l'accesso ai dati
* Funzionalità di sicurezza di oggetti e metadati
* Funzioni di protezione di amministrazione
* Funzioni di sicurezza della piattaforma
* Integrazione del cloud


Questo documento è destinato a essere una scheda tecnica di protezione, non descrive in dettaglio come configurare il sistema in modo che supporti le funzioni di protezione enumerate all'interno delle quali non sono configurate per impostazione predefinita. La https://docs.netapp.com/us-en/storagegrid-118/harden/index.html["Guida alla tempra StorageGRID"^] è disponibile nella pagina ufficiale https://docs.netapp.com/us-en/storagegrid-118/["Documentazione StorageGRID"^] .

Oltre alle funzionalità descritte in questo rapporto, StorageGRID segue la https://www.netapp.com/us/legal/vulnerability-response.aspx["Criteri di notifica e risposta alle vulnerabilità di protezione dei prodotti NetApp"^]. Le vulnerabilità segnalate vengono verificate e risolte in base al processo di risposta agli incidenti di sicurezza del prodotto.

NetApp StorageGRID offre funzionalità di sicurezza avanzate per casi di utilizzo dello storage a oggetti aziendale molto esigenti.



== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* NetApp StorageGRID: Valutazione della conformità SEC 17a-4(f), FINRA 4511(c) e CFTC 1,31(c)-(d) https://www.netapp.com/media/9041-ar-cohasset-netapp-storagegrid-sec-assessment.pdf[]
* Pagina della documentazione di StorageGRID 11,9 https://docs.netapp.com/us-en/storagegrid-119/[]
* Documentazione dei prodotti NetApp https://www.netapp.com/support-and-training/documentation/[]




== Termini e acronimi

In questa sezione vengono fornite le definizioni della terminologia utilizzata nel documento.

[cols="40,60"]
|===
| Termine o acronimo | Definizione 


| S3 | Simple Storage Service. 


| Client | Applicazione in grado di interfacciarsi con StorageGRID tramite il protocollo S3 per l'accesso ai dati o il protocollo HTTP per la gestione. 


| Amministratore tenant | L'amministratore dell'account tenant StorageGRID 


| Utente tenant | Un utente all'interno di un account tenant StorageGRID 


| TLS | Transport Layer Security 


| ILM | Gestione del ciclo di vita delle informazioni 


| LAN | Local Area Network (rete locale) 


| Amministratore di grid | L'amministratore del sistema StorageGRID 


| Griglia | Il sistema StorageGRID 


| Bucket | Un contenitore per gli oggetti memorizzati in S3 


| LDAP | Lightweight Directory Access Protocol 


| SEC. | Securities and Exchange Commission; regola i membri di Exchange, i broker o i dealer 


| FINRA | Autorità di regolamentazione del settore finanziario; difende i requisiti di formato e media della norma SEC 17a-4(f) 


| CFTC | Commodity Futures Trading Commission; regola il commodity futures trading 


| NIST | Istituto Nazionale di Standard e tecnologia 
|===