---
sidebar: sidebar 
permalink: technical-reports/data-security/object-metadata-security.html 
keywords: object metadata security, storagegrid 
summary: Esplora le funzionalità di sicurezza degli oggetti e dei metadati in StorageGRID. 
---
= Sicurezza di oggetti e metadati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Esplora le funzionalità di sicurezza degli oggetti e dei metadati in StorageGRID.

[cols="20,30a,30,20"]
|===
| Funzione | Funzione | Impatto | Conformità normativa 


| Crittografia degli oggetti lato server AES (Advanced Encryption Standard)  a| 
StorageGRID fornisce la crittografia degli oggetti sul lato server basata su AES 128 e AES 256. Gli amministratori della griglia possono abilitare la crittografia come impostazione predefinita globale. StorageGRID supporta inoltre l'intestazione di crittografia S3 x-amz-lato server per consentire l'attivazione o la disattivazione della crittografia in base all'oggetto. Se abilitato, gli oggetti vengono crittografati quando vengono archiviati o in transito tra i nodi della griglia.
| Aiuta a proteggere lo storage e la trasmissione degli oggetti, indipendentemente dall'hardware per lo storage sottostante. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Gestione delle chiavi integrata  a| 
Quando la crittografia è attivata, ogni oggetto viene crittografato con una chiave simmetrica univoca generata in modo casuale, memorizzata all'interno di StorageGRID senza accesso esterno.
| Consente la crittografia degli oggetti senza richiedere una gestione esterna delle chiavi. |  


| Dischi di crittografia conformi a Federal Information Processing Standard (FIPS) 140-2-2  a| 
Le appliance SG5712, SG5760, SG6060 e SGF6024 StorageGRID offrono l'opzione di dischi di crittografia conformi FIPS 140-2-2. Le chiavi di crittografia dei dischi possono essere facoltativamente gestite da un server KMIP esterno.
| Abilita lo storage sicuro di dati, metadati e oggetti di sistema. Fornisce inoltre una crittografia degli oggetti basata su software StorageGRID, che protegge storage e trasmissione di oggetti. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Scansione di integrità in background e autoriparazione  a| 
StorageGRID utilizza un meccanismo di interblocco costituito da hash, checksum e controlli di ridondanza ciclici (CRC) a livello di oggetto e sottooggetto per proteggere da incoerenza, manomissioni o modifiche dei dati, sia quando gli oggetti sono in storage che in transito. StorageGRID rileva automaticamente gli oggetti corrotti e manomessi e li sostituisce, mettendo in quarantena i dati modificati e avvisando l'amministratore.
| Permette agli amministratori di grid di soddisfare SLA, normative e altri obblighi in termini di conservazione dei dati. Aiuta i clienti a rilevare ransomware o virus che tentano di crittografare, manomettere o modificare i dati. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Conservazione e posizionamento degli oggetti basati su policy  a| 
StorageGRID consente agli amministratori di grid di configurare regole ILM che specificano conservazione, posizionamento, protezione, transizione e scadenza degli oggetti. Gli amministratori del grid possono configurare StorageGRID per filtrare gli oggetti in base ai propri metadati e applicare regole a vari livelli di granularità, tra cui Grid-wide, tenant, bucket, key prefix, coppie di valori chiave e metadati definiti dall'utente. StorageGRID contribuisce a garantire che gli oggetti vengano memorizzati in base alle regole ILM durante il loro ciclo di vita, a meno che non vengano esplicitamente eliminati dal client.
| Aiuta ad applicare il posizionamento, la protezione e la conservazione dei dati. Aiuta i clienti a raggiungere gli SLA relativi a durata, disponibilità e performance. | Regola SEC 17a-4(f) CTFC 1,31(c)-(d) (FINRA) regola 4511(c) 


| Scansione dei metadati in background  a| 
StorageGRID esegue periodicamente la scansione dei metadati degli oggetti in background per applicare modifiche al posizionamento o alla protezione dei dati degli oggetti come specificato da ILM.
| Aiuta a rilevare gli oggetti danneggiati. |  


| Uniformità regolabile  a| 
I tenant possono selezionare livelli di coerenza a livello del bucket per garantire che siano disponibili risorse come la connettività multisito.
| Offre l'opzione per eseguire il commit delle scritture sulla griglia solo quando è disponibile un numero richiesto di siti o risorse. |  
|===