---
permalink: product-feature-guides/create-cloud-storage-pool-aws-google-cloud.html 
sidebar: sidebar 
keywords: cloud storage pool, aws, S3, amazon web services, google cloud 
summary: 'È possibile utilizzare un pool di storage cloud se si desidera spostare gli oggetti StorageGRID in un bucket S3 esterno. Il bucket esterno può appartenere ad Amazon S3 (AWS) o Google Cloud.' 
---
= Creazione di un pool di storage cloud per AWS o Google Cloud
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare un pool di storage cloud se si desidera spostare gli oggetti StorageGRID in un bucket S3 esterno. Il bucket esterno può appartenere ad Amazon S3 (AWS) o Google Cloud.

.Di cosa hai bisogno
* StorageGRID 11.6 è stato configurato.
* Hai già configurato un bucket S3 esterno su AWS o Google Cloud.


.Fasi
. In Grid Manager, selezionare *ILM* > *Storage Pools*.
. Nella sezione Cloud Storage Pools della pagina, selezionare *Create*.
+
Viene visualizzata la finestra a comparsa Create Cloud Storage Pool (Crea pool di storage cloud).

. Inserire un nome visualizzato.
. Selezionare *Amazon S3* dall'elenco a discesa Provider Type (tipo di provider).
+
Questo tipo di provider funziona per AWS S3 o Google Cloud.

. Immettere l'URI per il bucket S3 da utilizzare per il Cloud Storage Pool.
+
Sono consentiti due formati:

+
`https://host:port`

+
`http://host:port`

. Immettere il nome del bucket S3.
+
Il nome specificato deve corrispondere esattamente al nome del bucket S3; in caso contrario, la creazione del pool di storage cloud non riesce. Non è possibile modificare questo valore dopo il salvataggio del Cloud Storage Pool.

. Se si desidera, inserire l'ID della chiave di accesso e la chiave di accesso segreta.
. Selezionare *non verificare certificato* dall'elenco a discesa.
. Fare clic su *Save* (Salva).


.Risultato previsto
Verificare che sia stato creato un Cloud Storage Pool per Amazon S3 o Google Cloud.

_Di Jonathan Wong_
