---
sidebar: sidebar 
permalink: technical-reports/bare-metal/start-storagegrid-host-service.html 
keywords: host service, storagegrid 
summary: Informazioni su come avviare il servizio host StorageGRID. 
---
= Avviare il servizio host StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Informazioni su come avviare il servizio host StorageGRID.

Per avviare i nodi StorageGRID e assicurarsi che vengano riavviati dopo il riavvio dell'host, è necessario attivare e avviare il servizio host StorageGRID.

Per avviare il servizio host StorageGRID, attenersi alla procedura riportata di seguito.

.Fasi
. Eseguire i seguenti comandi su ciascun host:
+
[listing]
----
sudo systemctl enable storagegrid
sudo systemctl start storagegrid
----
+

NOTE: Il processo di avvio potrebbe richiedere del tempo durante l'esecuzione iniziale.

. Eseguire il seguente comando per assicurarsi che l'implementazione stia procedendo:
+
[listing]
----
sudo storagegrid node status node-name
----
. Per qualsiasi nodo che restituisce uno stato di `Not-Running` o `Stopped`, eseguire il comando seguente:
+
[listing]
----
sudo storagegrid node start node-name
----
+
Ad esempio, dato il seguente output si avvierebbe il `dc1-adm1` nodo:

+
[listing]
----
[user@host1]# sudo storagegrid node status
Name Config-State Run-State
dc1-adm1 Configured Not-Running
dc1-sn1 Configured Running
----
. Se in precedenza è stato attivato e avviato il servizio host StorageGRID (o se non si è certi che il servizio sia stato attivato e avviato), eseguire anche il seguente comando:
+
[listing]
----
sudo systemctl reload-or-restart storagegrid
----

