---
sidebar: sidebar 
permalink: technical-reports/commvault/index.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Scopri alcuni casi di utilizzo per le configurazioni StorageGRID implementate dai clienti e da NetApp IT. 
---
= Eseguire backup e recovery di dati utilizzando StorageGRID e CommVault
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
CommVault e NetApp hanno collaborato alla creazione di una soluzione congiunta per la data Protection, che combina il software CommVault complete Backup and Recovery for NetApp con il software NetApp StorageGRID per il cloud storage. CommVault complete Backup and Recovery e NetApp StorageGRID forniscono soluzioni uniche e facili da utilizzare che collaborano per aiutarti a soddisfare le richieste di una rapida crescita dei dati e delle normative in aumento in tutto il mondo.

Molte organizzazioni vogliono migrare lo storage nel cloud, scalare i sistemi e automatizzare la policy per la conservazione dei dati a lungo termine. Lo storage a oggetti basato sul cloud è celebre per la sua resilienza, la sua capacità di scalare e le efficienze operative e legate ai costi, caratteristiche che lo rendono la scelta naturale come destinazione del backup. CommVault e NetApp hanno certificato congiuntamente la propria soluzione combinata nel 2014 e da allora hanno progettato una più profonda integrazione tra le due soluzioni. I clienti di ogni tipo in tutto il mondo hanno adottato la soluzione combinata di backup e recovery CommVault complete e StorageGRID.



== Informazioni su CommVault e StorageGRID

Il software CommVault complete Backup and Recovery è una soluzione di gestione integrata dei dati e delle informazioni di livello aziendale, costruita da zero su una singola piattaforma e con una base di codice unificata. Tutte le sue funzioni condividono tecnologie di back-end, apportando gli impareggiabili vantaggi e vantaggi di un approccio completamente integrato alla protezione, alla gestione e all'accesso ai dati. Il software contiene moduli per la protezione, l'archiviazione, l'analisi, la replica e la ricerca dei dati. I moduli condividono una serie comune di servizi back-end e funzionalità avanzate che interagiscono perfettamente tra loro. La soluzione affronta tutti gli aspetti della gestione dei dati nell'azienda, fornendo una scalabilità infinita e un controllo senza precedenti di dati e informazioni.

NetApp StorageGRID come Tier di cloud CommVault è una soluzione di storage a oggetti di cloud ibrido aziendale. Puoi implementarla su più siti, sia su un'appliance costruita ad hoc che come implementazione software-defined. StorageGRID ti consente di stabilire policy di gestione dei dati che determinano il modo in cui i dati vengono archiviati e protetti. StorageGRID raccoglie le informazioni necessarie per sviluppare e applicare le policy. Prende in esame un'ampia gamma di caratteristiche ed esigenze, tra cui performance, durata, disponibilità, posizione geografica, longevità e costi. I dati sono pienamente mantenuti e protetti durante lo spostamento tra posizioni e man mano che invecchiano.

Il motore di policy intelligente di StorageGRID consente di scegliere una delle seguenti opzioni:

* Utilizzare l'erasure coding per eseguire il backup dei dati su diversi siti allo scopo di ottenere resilienza.
* Copia degli oggetti in siti remoti per ridurre al minimo il costo e la latenza della WAN.


Quando StorageGRID archivia un oggetto, lo accedi come un unico oggetto, indipendentemente da dove si trova o dal numero di copie esistenti. Questo comportamento è fondamentale per il disaster recovery, perché con esso, anche se una copia di backup dei dati è danneggiata, StorageGRID è in grado di ripristinare i dati.

Conservare i dati di backup nello storage primario può rivelarsi costoso. Utilizzando NetApp StorageGRID, potrai liberare spazio sullo storage primario migrando i dati di backup inattivi in StorageGRID, senza rinunciare alle numerose funzionalità di StorageGRID. Il valore dei dati di backup cambia con il passare del tempo, così come il costo legato alla loro memorizzazione. StorageGRID può ridurre al minimo il costo dello storage primario aumentando al contempo la durata dei dati.



== Funzionalità principali

Le funzionalità principali della piattaforma software CommVault includono:

* Una soluzione completa di protezione dei dati che supporta tutti i principali sistemi operativi, database e applicazioni su server virtuali e fisici, sistemi NAS, infrastrutture basate sul cloud e dispositivi mobili.
* Gestione semplificata attraverso un'unica console: Puoi visualizzare, gestire e accedere a tutte le funzioni, tutti i dati e le informazioni dell'azienda.
* Diversi metodi di protezione, tra cui backup e archiviazione dei dati, gestione delle snapshot, replica dei dati e indicizzazione dei contenuti per l'e-Discovery.
* Gestione efficiente dello storage mediante la deduplica per il disco e il cloud storage.
* Integrazione con storage array NetApp come AFF, FAS, NetApp HCI ed e-Series e con i sistemi di storage scale-out NetApp SolidFire^®. Integrazione anche con il software NetApp Cloud Volumes ONTAP per automatizzare la creazione di copie Snapshot™ NetApp indicizzate e compatibili con le applicazioni nell'intero portafoglio di storage NetApp.
* Gestione completa dell'infrastruttura virtuale che supporta i principali hypervisor virtuali on-premise e piattaforme hyperscaler di cloud pubblico.
* Funzionalità di sicurezza avanzate per limitare l'accesso ai dati critici, offrire funzionalità di gestione granulari e fornire accesso single-sign-on agli utenti di Active Directory.
* Gestione dei dati basata su criteri che consente di gestire i dati in base alle esigenze aziendali, non in base a una posizione fisica.
* Un'esperienza utente finale all'avanguardia, che consente agli utenti di proteggere, trovare e ripristinare i propri dati.
* Automazione basata su API per utilizzare strumenti di terze parti come vRealize Automation o Service Now per gestire le operazioni di data Protection e recovery.


Per ulteriori informazioni sui carichi di lavoro supportati, visitare il sito Web https://www.commvault.com/supported-technologies["Tecnologie supportate da CommVault"].



== Opzioni di backup

Quando implementi il software di backup e recovery CommVault complete con il cloud storage, hai due opzioni di backup:

* Eseguire il backup su una destinazione disco primaria e una copia ausiliaria su cloud storage.
* Eseguire il backup sul cloud storage come destinazione primaria.


In passato, lo storage a oggetti o cloud era considerato dalle performance troppo basse per essere utilizzato per il backup primario. L'utilizzo di una destinazione disco primaria ha permesso ai clienti di disporre di processi di backup e ripristino più rapidi e di mantenere una copia ausiliaria nel cloud come backup cold. StorageGRID rappresenta la nuova generazione dello storage a oggetti. StorageGRID è in grado di offrire performance elevate, throughput elevato, performance e flessibilità superiori a quelle degli altri vendor di soluzioni storage a oggetti.

Nella seguente tabella sono elencati i vantaggi di ciascuna opzione di backup con StorageGRID:

[cols="1a,1a,1a"]
|===
|  | Backup primario su disco e copia ausiliaria su StorageGRID | Backup primario su StorageGRID 


 a| 
Performance
 a| 
Tempo di recovery più rapido, con montaggio live o live recovery: La soluzione migliore per i carichi di lavoro Tier0/Tier1.
 a| 
Non può essere utilizzato per operazioni di montaggio live o ripristino live. Ideale per le operazioni di ripristino in streaming e per la conservazione a lungo termine.



 a| 
Architettura di implementazione
 a| 
Utilizzo di una tecnologia all-flash o di un disco a rotazione come primo landing Tier di backup. StorageGRID viene utilizzato come Tier secondario.
 a| 
Semplifica l'implementazione utilizzando StorageGRID come destinazione di backup all-inclusive.



 a| 
Funzioni avanzate (ripristino in tempo reale)
 a| 
Supportato
 a| 
Non supportato

|===


== Dove trovare ulteriori informazioni

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* Centro di documentazione di StorageGRID 11,8 +
https://docs.netapp.com/us-en/storagegrid-118/[]
* Documentazione del prodotto NetApp +
https://docs.netapp.com[]
* Documentazione CommVault +
https://documentation.commvault.com/2024/essential/index.html[]

