---
sidebar: sidebar 
permalink: technical-reports/commvault/sizing.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Scopri alcuni casi di utilizzo per le configurazioni StorageGRID implementate dai clienti e da NetApp IT. 
---
= Guida al dimensionamento di StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Consulta i tuoi specialisti in materia di data Protection NetApp per dimensionamento specifico del tuo ambiente. Gli specialisti della data Protection di NetApp possono utilizzare lo strumento CommVault Total Backup Storage Calculator per stimare i requisiti dell'infrastruttura di backup. Lo strumento richiede l'accesso al portale per i partner CommVault. Se necessario, registrati per accedere.



== Input per il dimensionamento di CommVault

È possibile utilizzare le seguenti attività per eseguire il rilevamento per il dimensionamento della soluzione per la data Protection:

* Identifica i carichi di lavoro del sistema o dell'applicazione/database e la capacità front-end corrispondente (in terabyte [TB]) da proteggere.
* Identifica il carico di lavoro VM/file e la capacità front-end (TB) simile che deve essere protetta.
* Identificare i requisiti di conservazione a breve e a lungo termine.
* Identificare il change rate quotidiano in % per i set di dati/carichi di lavoro identificati.
* Identificazione della crescita dei dati prevista nei prossimi 12, 24 e 36 mesi.
* Definisci RTO e RPO per la data Protection/recovery in base alle esigenze di business.


Quando queste informazioni sono disponibili, è possibile eseguire il dimensionamento dell'infrastruttura di backup in modo da suddividere le capacità di storage richieste.



== Guida al dimensionamento di StorageGRID

Prima di eseguire il dimensionamento del NetApp StorageGRID, prendi in considerazione questi aspetti del carico di lavoro:

* Capacità utilizzabile
* Modalità WORM
* Dimensione media dell'oggetto
* Requisiti relativi alle performance
* Criterio ILM applicato


La quantità di capacità utilizzabile ha bisogno di per adattarsi alla dimensione del workload di backup su cui si è eseguito il tiering in StorageGRID e al programma di conservazione.

La modalità WORM sarà attivata o meno? Una volta abilitato WORM in CommVault, il blocco degli oggetti verrà configurato su StorageGRID. In questo modo si aumenterà la capacità dello storage a oggetti necessaria. La quantità di capacità richiesta varia in base alla durata di conservazione e al numero di modifiche agli oggetti per ogni backup.

Average object size è un parametro di input che aiuta nel dimensionamento delle performance in un ambiente StorageGRID. Le dimensioni medie degli oggetti utilizzate per un carico di lavoro CommVault dipendono dal tipo di backup.

La tabella seguente elenca le dimensioni medie degli oggetti per tipo di backup e descrive le letture del processo di ripristino dall'archivio di oggetti:

[cols="1a,1a,1a"]
|===
| Tipo di backup | Dimensione media oggetto | Ripristinare il comportamento 


 a| 
Eseguire una copia ausiliaria in StorageGRID
 a| 
32MB
 a| 
Lettura completa dell'oggetto 32MB



 a| 
Backup diretto su StorageGRID (deduplica abilitata)
 a| 
8MB
 a| 
1MB lettura casuale



 a| 
Backup diretto su StorageGRID (deduplica disattivata)
 a| 
32MB
 a| 
Lettura completa dell'oggetto 32MB

|===
Inoltre, la comprensione dei requisiti prestazionali per backup completi e backup incrementali consente di determinare il dimensionamento dei nodi di storage StorageGRID. I metodi di data Protection della policy ILM (Information Lifecycle management) di StorageGRID determinano la capacità necessaria per memorizzare i backup CommVault e influiscono sul dimensionamento del grid.

La replica ILM di StorageGRID è uno dei due meccanismi utilizzati da StorageGRID per memorizzare i dati degli oggetti. Quando StorageGRID assegna gli oggetti a una regola ILM che replica i dati, il sistema crea copie esatte dei dati degli oggetti e memorizza le copie nei nodi storage.

Erasure coding è il secondo metodo utilizzato da StorageGRID per memorizzare i dati degli oggetti. Quando StorageGRID assegna gli oggetti a una regola ILM configurata per creare copie con erasure coding, suddivide i dati degli oggetti in frammenti di dati. Calcola quindi ulteriori frammenti di parità e memorizza ogni frammento su un nodo storage diverso. Quando si accede a un oggetto, questo viene riassemblato utilizzando i frammenti memorizzati. Se un frammento di dati o un frammento di parità si danneggia o viene perso, l'algoritmo di erasure coding può ricreare quel frammento utilizzando un sottoinsieme dei dati e dei frammenti di parità rimanenti.

I due meccanismi richiedono diverse quantità di storage, come dimostrano questi esempi:

* Se si memorizzano due copie replicate, il carico di storage raddoppia.
* Se si archivia una copia con erasure coding 2+1, l'overhead dello storage aumenta di 1,5 volte.


Per la soluzione sottoposta a test, è stata utilizzata un'implementazione StorageGRID entry-level su un singolo sito:

* Nodo amministrativo: Macchina virtuale VMware (VM)
* Bilanciamento del carico: VMware VM
* Nodi storage: 4x SG5712 PB con 4TB dischi
* Nodo amministrativo primario e nodo gateway: Macchine virtuali VMware con i requisiti minimi del carico di lavoro di produzione


[NOTE]
====
StorageGRID supporta anche i sistemi di bilanciamento del carico di terze parti.

====
Di solito, StorageGRID viene implementato in due o più siti con policy di data Protection che replicano i dati per proteggersi dai guasti a livello di nodo e di sito. Effettuando il backup dei dati su StorageGRID, i dati saranno protetti da copie multiple o dall'erasure coding che separa e riassembla i dati in modo affidabile attraverso un algoritmo.

È possibile utilizzare lo strumento di dimensionamento https://fusion.netapp.com["Fusion"] per dimensionare la griglia.



== Scalabilità

È possibile espandere un sistema NetApp StorageGRID aggiungendo storage ai nodi storage, aggiungendo nuovi nodi grid a un sito esistente o aggiungendo un nuovo sito per il data center. È possibile eseguire espansioni senza interrompere il funzionamento del sistema corrente.
StorageGRID scala le performance utilizzando nodi con performance più elevate per i nodi storage o l'appliance fisica che esegue il bilanciamento del carico e i nodi amministrativi o semplicemente aggiungendo nodi aggiuntivi.

[NOTE]
====
Per ulteriori informazioni sull'espansione del sistema StorageGRID, vedere https://docs.netapp.com/us-en/storagegrid-119/landing-expand/index.html["Guida all'espansione di StorageGRID 11,9"].

====